export const headerNav = [
  { label: "home", path: "/" },
  { label: "about", path: "/about" },
  { label: "링크컴포넌트 활용하기", path: "/linktest" },
  { label: "navigate객체 활용하기", path: "/navigatetest" },
  // { label: "1번 회원 조회", path: "/users/1" },
  // { label: "2번 회원 조회", path: "/users/2" },
  { label: "회원조회", path: "/users" },
];

export const users = [
  {
    id: 1,
    name: "김철수",
    email: "chulsoo.kim@example.com",
    age: 28,
    job: "Frontend Developer",
    isActive: true,
  },
  {
    id: 2,
    name: "이영희",
    email: "younghee.lee@example.com",
    age: 32,
    job: "UI/UX Designer",
    isActive: true,
  },
  {
    id: 3,
    name: "박민수",
    email: "minsu.park@example.com",
    age: 25,
    job: "Backend Developer",
    isActive: false,
  },
  {
    id: 4,
    name: "정수진",
    email: "sujin.jung@example.com",
    age: 29,
    job: "Project Manager",
    isActive: true,
  },
  {
    id: 5,
    name: "최동현",
    email: "donghyun.choi@example.com",
    age: 35,
    job: "DevOps Engineer",
    isActive: true,
  },
  {
    id: 6,
    name: "강지현",
    email: "jihyun.kang@example.com",
    age: 27,
    job: "Marketing Manager",
    isActive: false,
  },
  {
    id: 7,
    name: "조성민",
    email: "sungmin.cho@example.com",
    age: 31,
    job: "Full Stack Developer",
    isActive: true,
  },
  {
    id: 8,
    name: "윤서연",
    email: "seoyeon.yoon@example.com",
    age: 24,
    job: "Intern",
    isActive: true,
  },
  {
    id: 9,
    name: "장우성",
    email: "woosung.jang@example.com",
    age: 40,
    job: "CTO",
    isActive: true,
  },
  {
    id: 10,
    name: "임하은",
    email: "haeun.lim@example.com",
    age: 26,
    job: "Data Analyst",
    isActive: false,
  },
];
